### ISSUE TITLE
Cannot update bucket details from UI when NodeBB is hosted in a subfolder

### ISSUE THREAD

**Issue by skarungan** [LewisMcMahon/nodebb-plugin-s3-uploads#12]
I have NodeBB hosted in sub-url path `http://domain.com/forum`. While saving the bucket name from the UI, the api call is made to `http://domain.com/api/admin/plugins/s3-uploads/s3settings` instead of `http://domain.com/forum/api/admin/plugins/s3-uploads/s3settings`

So, S3 settings update fails from UI. 

I do have `/form` in my `config.json`. Everything else works well

**Comment by LewisMcMahon** [comment]
Do you mean the api call that NodeBB makes to save settings?

**Comment by skarungan** [comment]
Yes @LewisMcMahon

**Comment by LewisMcMahon** [comment]
Could you share your config.json

On 8 July 2016 00:11:58 BST, Shan notifications@github.com wrote:

> Yes @LewisMcMahon 
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/LewisMcMahon/nodebb-plugin-s3-uploads/issues/12#issuecomment-231234509

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by skarungan** [comment]
Thanks @LewisMcMahon. This is my config.json. 

```
{
    "url": "https://subdomain.domain.com/forum",
    "secret": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "database": "redis",
    "port": 4567,
    "redis": {
        "host": "xxxxxxxxxxxxx,
        "port": "6379",
        "database": "0"
    }
}
```

**Comment by LewisMcMahon** [comment]
ive just pushed v0.3.11 to npm that should fix the issue if not tell me and ill setup a subfolder install tomorow and do some proper testing

**Comment by skarungan** [comment]
Thanks @LewisMcMahon It worked
`/forum/api/admin/plugins/s3-uploads/credentials` I see the API call to save the S3 details made to proper URL and succeeded.

**Comment by LewisMcMahon** [comment]
Awsom, thanks for reporting it.

---

Lewis McMahon

www.lewismcmahon.co.uk
+4478 5650 7793
