### ISSUE TITLE
Unable to upload images and files

### ISSUE THREAD

**Issue by stefaniesoh** [LewisMcMahon/nodebb-plugin-s3-uploads#13]
Below is what I see when I tried uploading an image.

![0_1468979555815_1464346253798-laksa_slide1.png](Uploading 0%)

**Comment by LewisMcMahon** [comment]
What are your settings?
Are any files being put into s3?

**Comment by stefaniesoh** [comment]
Hi Lewis, thank you for replying.

I am hosting with nodeBB and I didn't use environment variable nor instance meta-data for S3 upload plugin. The last successful upload to S3 was 15th July.

The upload to S3 was working all the time and files are being placed in S3 until Julian helped us to migrate our stuff to a server in Singapore. Somehow it stopped working, I'm not sure if this is a coincident.

I filled up the following confirgation:

Database Stored configuration:
- Bucket
- Path
- Region

Credentials
- Access Key ID
- Secret Access Key

**Comment by stefaniesoh** [comment]
Saw this in my log

22/7 01:59 [21308] - [33mwarn[39m: [plugins/nodebb-plugin-s3-uploads-updated] Mapped path 's3 => /home/saas/nodebb/node_modules/nodebb-plugin-s3-uploads-updated/public' not found.

**Comment by LewisMcMahon** [comment]
If its not been working since a migration please talk to the people that did your migration first.

**Comment by maidoesthings** [comment]
I'm seeing this issue too. Do we need to set a CORs configuration or a bucket policy for the S3 bucket?

**Comment by LouiseMcMahon** [comment]
could you make a new issue with your issue and some more info of your own please ill close this one as the op never came back
