### ISSUE TITLE
The XML you provided was not well-formed or did not validate against our published schema

### ISSUE THREAD

**Issue by maidoesthings** [LewisMcMahon/nodebb-plugin-s3-uploads#15]
Trying to upload an image to NodeBB and I'm getting this error in the admin control panel. In the browser console, it says

`Failed to load resource: the server responded with a status of 502 (Bad Gateway)
https://{url}/api/admin/uploadlogo Failed to load resource: the server responded with a status of 500 (Internal Server Error)`

**Edit**
We were exporting the keys and S3_UPLOADS_BUCKET in the environment, which is when we were getting that error. But after entering only the S3_UPLOADS_BUCKET in the admin control panel, it started working.

**Comment by LouiseMcMahon** [comment]
Thaks for the update ill close this. Just an FYI if you add an edit I don't get a notification best to always add stuff like that as a comment.
