### ISSUE TITLE
Issues uploading to s3

### ISSUE THREAD

**Issue by cjinfantino** [LewisMcMahon/nodebb-plugin-s3-uploads#21]
I am getting the following error when trying to add an image to a post:

"nodebb-plugin-s3-uploads-updated :: Missing credentials in config"

I setup the bucket name and path in the DB section and created and IAM user with permission to the bucket in AWS. 

I'm not sure exactly where I setup the credentials for the user in the plugin.

**Comment by LouiseMcMahon** [comment]
You can either set them by environment variables or in the settings which you will find in the nav bar.

**Comment by cjinfantino** [comment]
What "nav bar". Are you referring to the settings->plugin->s3 configs? The only options I see to input are to store in the DB. 

And if I used ENV variables how would you make them persist? And doesn't that defeat the purpose because it's stored in plain text somewhere.

**Comment by cjinfantino** [comment]
I was able to get it to work via env variables. 

I noticed that all the uploads are getting public open/download permissions. I was thinking that the plugin would be querying aws to view the file via the access_id setup. 

But it appears the file needs to be public. Is this the case?

**Comment by LouiseMcMahon** [comment]
Yes it just hotlinks the files

**Comment by LouiseMcMahon** [comment]
also if you scroll down in that settings page area you should see `Credentials` thats where you put the aws key
