### ISSUE TITLE
Unable to save entries. Nodebb 1.4.3 and Redis

### ISSUE THREAD

**Issue by GitPuffy** [LewisMcMahon/nodebb-plugin-s3-uploads#22]
I receive an error when attempting to save my bucket or credential information via this plugins control panel.  The error displayed is simply:

`Error   Error saving!`

I am using NodeBB `v1.4.3` and `redis`

**Comment by LouiseMcMahon** [comment]
Do you get an error message in the console if you start nodebb in dev mode?

**Comment by GitPuffy** [comment]
Testing this with `./nodebb dev` does not show an error logged at the console.  I only receive the error in my browser after I click `SAVE`.

**Comment by LouiseMcMahon** [comment]
Ok, can you give me a bit more info on exactly what your doing screenshots would be great? Obviously, dont show your AWSkeys.

Also what node version are you on and what browser and version?

**Comment by GitPuffy** [comment]
This is in my "DEV" environment which is a copy of my production environment.  I have done "this" numerous times before and it has worked.  With that said I did test making a change to my bucket in my production environment and I am not getting errors.  

I am going to destroy my dev environment and make a new copy of production and test again.

`node -v` is `v6.9.5`
`npm -v` is `3.10.10`

**Comment by GitPuffy** [comment]
Nevermind.  The error was on my side.

After I made the copy of my prod environment and updated my config.json with the new port and database information I failed to update the URL!  So, the URL of my dev environment was still pointing to the URL of my production.  That little thing was enough to make updating the plugin not work.

I am sorry to trouble you for nothing.

**Comment by LouiseMcMahon** [comment]
No problem thanks for updating me.
