### ISSUE TITLE
invalid url generated for user images

### ISSUE THREAD

**Issue by yoann-antoviaque** [LewisMcMahon/nodebb-plugin-s3-uploads#5]
in https://github.com/LewisMcMahon/nodebb-plugin-s3-uploads/blob/master/index.js#L312 we can see that the host is prefixed with // to handle http and https

but nodebb, searches for http to decide if it is a relative url or not, therefore, urls are seen as relative to nodebb installation and prefixed with nodebb's path (https://github.com/NodeBB/NodeBB/blob/master/src/user/data.js#L115)

I think there should be an option to set http or https, or simply specify it in the host, that would fix this issue while still allowing both

**Comment by LewisMcMahon** [comment]
Can you tell me how to test this? are we talking about user profile pictures?

**Comment by yoann-antoviaque** [comment]
yes, I was talking about user profile picture.

To test it, just install nodebb with a non empty relative_path, login and go to the user profile, change profile picture, the browser will try to download a picture from the nodebb server with path containing the configured host (or the bucket name if no host is configured).

I'm working on a patch to submit and will attached it once I can confirm the fix

**Comment by LewisMcMahon** [comment]
I would be ok with just hard coding the https as all s3 buckets are https enabled now they were now when the plugin was originally written.

**Comment by LewisMcMahon** [comment]
Also if you wish to push a fix thats great but please make sure to read the [contribution guidelines](https://github.com/LewisMcMahon/nodebb-plugin-s3-uploads/blob/master/.github/CONTRIBUTING.md)

**Comment by yoann-antoviaque** [comment]
I've submitted a new pull request that should respect the guidelines... sorry

**Comment by LewisMcMahon** [comment]
thanks
