### ISSUE TITLE
Need to check IAM Roles work

### ISSUE THREAD

**Issue by LewisMcMahon** [LewisMcMahon/nodebb-plugin-s3-uploads#8]
Check if IAM roles work and if not make them then document it

**Comment by jameswann** [comment]
IAM roles work. I was able to create an IAM role with the following policy and get it working with uploads.

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1234567890",
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": [
                "arn:aws:s3:::bucketname/*"
            ]
        }
    ]
}`

**Comment by LouiseMcMahon** [comment]
Thanks :)
