### ISSUE TITLE
How to use s3 url instead of site url? 

### ISSUE THREAD

**Issue by chavenor** [LewisMcMahon/nodebb-plugin-s3-uploads#9]
How do I use the s3 url instead of the site url?

**Comment by LewisMcMahon** [comment]
Your going to need to be more specific.

On 24 May 2016 03:28:18 BST, Casey Havenor notifications@github.com wrote:

> How do I use the s3 url instead of the site url?   
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/LewisMcMahon/nodebb-plugin-s3-uploads/issues/9

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by chavenor** [comment]
![f6a3837e8745c8d530a31cbe16034476](https://cloud.githubusercontent.com/assets/1850981/15491030/4ffa1236-2132-11e6-8346-e793b0c7ae06.jpg)

**Comment by chavenor** [comment]
When I drag and drop I'd like to use the s3 file instead of the website file since I'm on a heroku setup and the static files won't stick after the dyno restart.

![no-data](https://cloud.githubusercontent.com/assets/1850981/15491033/59e540a4-2132-11e6-8007-ee414697f779.gif)

**Comment by LewisMcMahon** [comment]
What is your host setting set to? If you leave it blank it will use the s3 url

**Comment by chavenor** [comment]
![hosting](https://cloud.githubusercontent.com/assets/1850981/15497513/bb8c4ae0-2160-11e6-87d1-ce6e61c71365.png)

**Comment by LewisMcMahon** [comment]
Set it blank along with path and everything should work. the host is not supposed to be your website host and path but the S3 host and path.

**Comment by chavenor** [comment]
Well done sir.  Can I buy you a cup of coffee/donations?

**Comment by LewisMcMahon** [comment]
Your welcome to submit a PR to the readme that makes this a bit more clear.
